/* Hágil Terapêutica — catálogo Campo Vivo.
   GERADO POR scripts/gerar_catalogo.py — não editar à mão.

   38 produtos únicos · 9 espécies.
*/
window.HAGIL_CATALOGO = {
  produtos: [
  {
    "id": "actio",
    "nome": "Actio",
    "foto": "assets/images/produtos/Hagil_Pet_Actio.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Pet_Actio.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Pet_Actio-card.webp",
    "largura": 935,
    "altura": 1100,
    "cardLargura": 391,
    "cardAltura": 460,
    "largo": false,
    "familia": "Actio",
    "familiaSlug": "actio",
    "especie": "pet",
    "especies": [
      "pet"
    ],
    "categorias": [
      "pet"
    ],
    "segmentos": [],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Pet",
    "busca": "actio actio pet "
  },
  {
    "id": "actio-creme-para-pentear",
    "nome": "Actio Creme para Pentear",
    "foto": "assets/images/produtos/Hagil_Pet_Actio Creme para Pentear.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Pet_Actio Creme para Pentear.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Pet_Actio Creme para Pentear-card.webp",
    "largura": 583,
    "altura": 1100,
    "cardLargura": 244,
    "cardAltura": 460,
    "largo": false,
    "familia": "Actio Creme para Pentear",
    "familiaSlug": "actio-creme-para-pentear",
    "especie": "pet",
    "especies": [
      "pet"
    ],
    "categorias": [
      "pet"
    ],
    "segmentos": [],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Pet",
    "busca": "actio creme para pentear actio creme para pentear pet "
  },
  {
    "id": "actio-shampoo",
    "nome": "Actio Shampoo",
    "foto": "assets/images/produtos/Hagil_Pet_Actio Shampoo.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Pet_Actio Shampoo.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Pet_Actio Shampoo-card.webp",
    "largura": 583,
    "altura": 1100,
    "cardLargura": 244,
    "cardAltura": 460,
    "largo": false,
    "familia": "Actio Shampoo",
    "familiaSlug": "actio-shampoo",
    "especie": "pet",
    "especies": [
      "pet"
    ],
    "categorias": [
      "pet"
    ],
    "segmentos": [],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Pet",
    "busca": "actio shampoo actio shampoo pet "
  },
  {
    "id": "aliviatto",
    "nome": "Aliviatto",
    "foto": "assets/images/produtos/Hagil_Bovinos_Bovinos 1ª Fase_Aliviatto.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Aliviatto.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Aliviatto-card.webp",
    "largura": 609,
    "altura": 1100,
    "cardLargura": 255,
    "cardAltura": 460,
    "largo": false,
    "familia": "Aliviatto",
    "familiaSlug": "aliviatto",
    "especie": "bovinos",
    "especies": [
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "pet",
      "suinos"
    ],
    "categorias": [
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "pet",
      "suinos"
    ],
    "segmentos": [
      "Bovinos 1ª Fase",
      "Bovinos de Corte",
      "Bovinos de Leite"
    ],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Multiespécie (7 espécies)",
    "busca": "aliviatto aliviatto bovinos bubalinos caprinos equinos ovinos pet suinos bovinos 1ª fase bovinos de corte bovinos de leite"
  },
  {
    "id": "andhir",
    "nome": "Andhir",
    "foto": "assets/images/produtos/Hagil_Pet_Andhir.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Pet_Andhir.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Pet_Andhir-card.webp",
    "largura": 937,
    "altura": 1100,
    "cardLargura": 392,
    "cardAltura": 460,
    "largo": false,
    "familia": "Andhir",
    "familiaSlug": "andhir",
    "especie": "pet",
    "especies": [
      "pet"
    ],
    "categorias": [
      "pet"
    ],
    "segmentos": [],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Pet",
    "busca": "andhir andhir pet "
  },
  {
    "id": "arlevh",
    "nome": "Arlevh",
    "foto": "assets/images/produtos/Hagil_Pet_Arlevh.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Pet_Arlevh.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Pet_Arlevh-card.webp",
    "largura": 937,
    "altura": 1100,
    "cardLargura": 392,
    "cardAltura": 460,
    "largo": false,
    "familia": "Arlevh",
    "familiaSlug": "arlevh",
    "especie": "pet",
    "especies": [
      "pet"
    ],
    "categorias": [
      "pet"
    ],
    "segmentos": [],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Pet",
    "busca": "arlevh arlevh pet "
  },
  {
    "id": "avivar-pet",
    "nome": "Avivar pet",
    "foto": "assets/images/produtos/Hagil_Pet_Avivar pet.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Pet_Avivar pet.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Pet_Avivar pet-card.webp",
    "largura": 326,
    "altura": 1100,
    "cardLargura": 136,
    "cardAltura": 460,
    "largo": false,
    "familia": "Avivar",
    "familiaSlug": "avivar",
    "especie": "pet",
    "especies": [
      "pet"
    ],
    "categorias": [
      "pet"
    ],
    "segmentos": [],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Pet",
    "busca": "avivar pet avivar pet "
  },
  {
    "id": "billifort",
    "nome": "Billifort",
    "foto": "assets/images/produtos/Hagil_Pet_Billifort.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Pet_Billifort.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Pet_Billifort-card.webp",
    "largura": 937,
    "altura": 1100,
    "cardLargura": 392,
    "cardAltura": 460,
    "largo": false,
    "familia": "Billifort",
    "familiaSlug": "billifort",
    "especie": "pet",
    "especies": [
      "pet"
    ],
    "categorias": [
      "pet"
    ],
    "segmentos": [],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Pet",
    "busca": "billifort billifort pet "
  },
  {
    "id": "ciclantur-h1000",
    "nome": "Ciclantur H1000",
    "foto": "assets/images/produtos/Hagil_Bovinos_Bovinos de Corte_Ciclantur H1000.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos de Corte_Ciclantur H1000.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos de Corte_Ciclantur H1000-card.webp",
    "largura": 841,
    "altura": 1100,
    "cardLargura": 352,
    "cardAltura": 460,
    "largo": false,
    "familia": "Ciclantur",
    "familiaSlug": "ciclantur",
    "especie": "bovinos",
    "especies": [
      "aves",
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "suinos"
    ],
    "categorias": [
      "aves",
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "suinos"
    ],
    "segmentos": [
      "Aves de Postura",
      "Bovinos de Corte",
      "Bovinos de Leite"
    ],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Multiespécie (7 espécies)",
    "busca": "ciclantur h1000 ciclantur aves bovinos bubalinos caprinos equinos ovinos suinos aves de postura bovinos de corte bovinos de leite"
  },
  {
    "id": "curae-hc1000",
    "nome": "Curae HC1000",
    "foto": "assets/images/produtos/Hagil_Bovinos_Bovinos 1ª Fase_Curae HC1000.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Curae HC1000.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Curae HC1000-card.webp",
    "largura": 828,
    "altura": 1100,
    "cardLargura": 346,
    "cardAltura": 460,
    "largo": false,
    "familia": "Curae",
    "familiaSlug": "curae",
    "especie": "bovinos",
    "especies": [
      "aves",
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "peixes",
      "suinos"
    ],
    "categorias": [
      "aves",
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "peixes",
      "suinos"
    ],
    "segmentos": [
      "Aves de Corte",
      "Aves de Postura",
      "Bovinos 1ª Fase",
      "Bovinos de Corte"
    ],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Multiespécie (8 espécies)",
    "busca": "curae hc1000 curae aves bovinos bubalinos caprinos equinos ovinos peixes suinos aves de corte aves de postura bovinos 1ª fase bovinos de corte"
  },
  {
    "id": "curae-pet",
    "nome": "Curae PET",
    "foto": "assets/images/produtos/Hagil_Pet_Curae PET.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Pet_Curae PET.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Pet_Curae PET-card.webp",
    "largura": 498,
    "altura": 1100,
    "cardLargura": 208,
    "cardAltura": 460,
    "largo": false,
    "familia": "Curae",
    "familiaSlug": "curae",
    "especie": "pet",
    "especies": [
      "pet"
    ],
    "categorias": [
      "pet"
    ],
    "segmentos": [],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Pet",
    "busca": "curae pet curae pet "
  },
  {
    "id": "dhermus",
    "nome": "Dhermus",
    "foto": "assets/images/produtos/Hagil_Pet_Dhermus.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Pet_Dhermus.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Pet_Dhermus-card.webp",
    "largura": 937,
    "altura": 1100,
    "cardLargura": 392,
    "cardAltura": 460,
    "largo": false,
    "familia": "Dhermus",
    "familiaSlug": "dhermus",
    "especie": "pet",
    "especies": [
      "pet"
    ],
    "categorias": [
      "pet"
    ],
    "segmentos": [],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Pet",
    "busca": "dhermus dhermus pet "
  },
  {
    "id": "dhermus-creme",
    "nome": "Dhermus Creme",
    "foto": "assets/images/produtos/Hagil_Pet_Dhermus Creme.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Pet_Dhermus Creme.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Pet_Dhermus Creme-card.webp",
    "largura": 404,
    "altura": 1100,
    "cardLargura": 169,
    "cardAltura": 460,
    "largo": false,
    "familia": "Dhermus Creme",
    "familiaSlug": "dhermus-creme",
    "especie": "pet",
    "especies": [
      "pet"
    ],
    "categorias": [
      "pet"
    ],
    "segmentos": [],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Pet",
    "busca": "dhermus creme dhermus creme pet "
  },
  {
    "id": "durin",
    "nome": "Durin",
    "foto": "assets/images/produtos/Hagil_Pet_Durin.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Pet_Durin.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Pet_Durin-card.webp",
    "largura": 938,
    "altura": 1100,
    "cardLargura": 392,
    "cardAltura": 460,
    "largo": false,
    "familia": "Durin",
    "familiaSlug": "durin",
    "especie": "pet",
    "especies": [
      "pet"
    ],
    "categorias": [
      "pet"
    ],
    "segmentos": [],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Pet",
    "busca": "durin durin pet "
  },
  {
    "id": "dynamis-mh1000",
    "nome": "Dynamis MH1000",
    "foto": "assets/images/produtos/Hagil_Bovinos_Bovinos 1ª Fase_Dynamis MH1000.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Dynamis MH1000.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Dynamis MH1000-card.webp",
    "largura": 828,
    "altura": 1100,
    "cardLargura": 346,
    "cardAltura": 460,
    "largo": false,
    "familia": "Dynamis",
    "familiaSlug": "dynamis",
    "especie": "bovinos",
    "especies": [
      "aves",
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "peixes",
      "suinos"
    ],
    "categorias": [
      "aves",
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "peixes",
      "suinos"
    ],
    "segmentos": [
      "Aves de Corte",
      "Aves de Postura",
      "Bovinos 1ª Fase",
      "Bovinos de Corte",
      "Bovinos de Leite"
    ],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Multiespécie (8 espécies)",
    "busca": "dynamis mh1000 dynamis aves bovinos bubalinos caprinos equinos ovinos peixes suinos aves de corte aves de postura bovinos 1ª fase bovinos de corte bovinos de leite"
  },
  {
    "id": "dynamis-pet",
    "nome": "Dynamis pet",
    "foto": "assets/images/produtos/Hagil_Pet_Dynamis pet.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Pet_Dynamis pet.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Pet_Dynamis pet-card.webp",
    "largura": 1437,
    "altura": 1100,
    "cardLargura": 601,
    "cardAltura": 460,
    "largo": true,
    "familia": "Dynamis",
    "familiaSlug": "dynamis",
    "especie": "pet",
    "especies": [
      "pet"
    ],
    "categorias": [
      "pet"
    ],
    "segmentos": [],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Pet",
    "busca": "dynamis pet dynamis pet "
  },
  {
    "id": "ecthon-hb1000",
    "nome": "Ecthon HB1000",
    "foto": "assets/images/produtos/Hagil_Bovinos_Bovinos 1ª Fase_Ecthon HB1000.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Ecthon HB1000.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Ecthon HB1000-card.webp",
    "largura": 676,
    "altura": 1100,
    "cardLargura": 283,
    "cardAltura": 460,
    "largo": false,
    "familia": "Ecthon",
    "familiaSlug": "ecthon",
    "especie": "bovinos",
    "especies": [
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "pet"
    ],
    "categorias": [
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "pet"
    ],
    "segmentos": [
      "Bovinos 1ª Fase",
      "Bovinos de Corte",
      "Bovinos de Leite"
    ],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Multiespécie (5 espécies)",
    "busca": "ecthon hb1000 ecthon bovinos bubalinos caprinos equinos pet bovinos 1ª fase bovinos de corte bovinos de leite"
  },
  {
    "id": "ecthon-pour-on",
    "nome": "Ecthon Pour-On",
    "foto": "assets/images/produtos/Hagil_Bovinos_Bovinos 1ª Fase_Ecthon Pour-On.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Ecthon Pour-On.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Ecthon Pour-On-card.webp",
    "largura": 752,
    "altura": 1100,
    "cardLargura": 315,
    "cardAltura": 460,
    "largo": false,
    "familia": "Ecthon Pour-On",
    "familiaSlug": "ecthon-pour-on",
    "especie": "bovinos",
    "especies": [
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "suinos"
    ],
    "categorias": [
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "suinos"
    ],
    "segmentos": [
      "Bovinos 1ª Fase",
      "Bovinos de Corte",
      "Bovinos de Leite"
    ],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Multiespécie (5 espécies)",
    "busca": "ecthon pour-on ecthon pour-on bovinos bubalinos caprinos equinos suinos bovinos 1ª fase bovinos de corte bovinos de leite"
  },
  {
    "id": "endecthon-hp1000",
    "nome": "Endecthon HP1000",
    "foto": "assets/images/produtos/Hagil_Bovinos_Bovinos 1ª Fase_Endecthon HP1000.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Endecthon HP1000.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Endecthon HP1000-card.webp",
    "largura": 843,
    "altura": 1100,
    "cardLargura": 352,
    "cardAltura": 460,
    "largo": false,
    "familia": "Endecthon",
    "familiaSlug": "endecthon",
    "especie": "bovinos",
    "especies": [
      "aves",
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "peixes",
      "suinos"
    ],
    "categorias": [
      "aves",
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "peixes",
      "suinos"
    ],
    "segmentos": [
      "Aves de Corte",
      "Aves de Postura",
      "Bovinos 1ª Fase",
      "Bovinos de Corte",
      "Bovinos de Leite"
    ],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Multiespécie (8 espécies)",
    "busca": "endecthon hp1000 endecthon aves bovinos bubalinos caprinos equinos ovinos peixes suinos aves de corte aves de postura bovinos 1ª fase bovinos de corte bovinos de leite"
  },
  {
    "id": "entherikos",
    "nome": "Enthérikos",
    "foto": "assets/images/produtos/Hagil_Bovinos_Bovinos 1ª Fase_Enthérikos.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Enthérikos.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Enthérikos-card.webp",
    "largura": 1571,
    "altura": 596,
    "cardLargura": 1213,
    "cardAltura": 460,
    "largo": true,
    "familia": "Enthérikos",
    "familiaSlug": "entherikos",
    "especie": "bovinos",
    "especies": [
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "suinos"
    ],
    "categorias": [
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "suinos"
    ],
    "segmentos": [
      "Bovinos 1ª Fase",
      "Bovinos de Corte",
      "Bovinos de Leite"
    ],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Multiespécie (6 espécies)",
    "busca": "entherikos entherikos bovinos bubalinos caprinos equinos ovinos suinos bovinos 1ª fase bovinos de corte bovinos de leite"
  },
  {
    "id": "entherikos-pet",
    "nome": "Enthérikos Pet",
    "foto": "assets/images/produtos/Hagil_Pet_Enthérikos Pet.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Pet_Enthérikos Pet.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Pet_Enthérikos Pet-card.webp",
    "largura": 1572,
    "altura": 597,
    "cardLargura": 1211,
    "cardAltura": 460,
    "largo": true,
    "familia": "Enthérikos",
    "familiaSlug": "entherikos",
    "especie": "pet",
    "especies": [
      "pet"
    ],
    "categorias": [
      "pet"
    ],
    "segmentos": [],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Pet",
    "busca": "entherikos pet entherikos pet "
  },
  {
    "id": "ethos",
    "nome": "Ethos",
    "foto": "assets/images/produtos/Hagil_Pet_Ethos.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Pet_Ethos.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Pet_Ethos-card.webp",
    "largura": 935,
    "altura": 1100,
    "cardLargura": 391,
    "cardAltura": 460,
    "largo": false,
    "familia": "Ethos",
    "familiaSlug": "ethos",
    "especie": "pet",
    "especies": [
      "pet"
    ],
    "categorias": [
      "pet"
    ],
    "segmentos": [],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Pet",
    "busca": "ethos ethos pet "
  },
  {
    "id": "hepathor-h1000",
    "nome": "Hepathor H1000",
    "foto": "assets/images/produtos/Hagil_Bovinos_Bovinos 1ª Fase_Hepathor H1000.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Hepathor H1000.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Hepathor H1000-card.webp",
    "largura": 829,
    "altura": 1100,
    "cardLargura": 347,
    "cardAltura": 460,
    "largo": false,
    "familia": "Hepathor",
    "familiaSlug": "hepathor",
    "especie": "bovinos",
    "especies": [
      "aves",
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "peixes",
      "suinos"
    ],
    "categorias": [
      "aves",
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "peixes",
      "suinos"
    ],
    "segmentos": [
      "Aves de Corte",
      "Aves de Postura",
      "Bovinos 1ª Fase",
      "Bovinos de Corte",
      "Bovinos de Leite"
    ],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Multiespécie (8 espécies)",
    "busca": "hepathor h1000 hepathor aves bovinos bubalinos caprinos equinos ovinos peixes suinos aves de corte aves de postura bovinos 1ª fase bovinos de corte bovinos de leite"
  },
  {
    "id": "hmais-h1000",
    "nome": "HMAIS H1000",
    "foto": "assets/images/produtos/Hagil_Peixes_HMAIS H1000.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Peixes_HMAIS H1000.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Peixes_HMAIS H1000-card.webp",
    "largura": 856,
    "altura": 1100,
    "cardLargura": 358,
    "cardAltura": 460,
    "largo": false,
    "familia": "HMAIS",
    "familiaSlug": "hmais",
    "especie": "peixes",
    "especies": [
      "peixes"
    ],
    "categorias": [
      "peixes"
    ],
    "segmentos": [],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Peixes",
    "busca": "hmais h1000 hmais peixes "
  },
  {
    "id": "intramasthe-10",
    "nome": "IntraMasthe 10",
    "foto": "assets/images/produtos/Hagil_Bovinos_Bovinos de Leite_IntraMasthe 10.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos de Leite_IntraMasthe 10.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos de Leite_IntraMasthe 10-card.webp",
    "largura": 795,
    "altura": 1100,
    "cardLargura": 332,
    "cardAltura": 460,
    "largo": false,
    "familia": "IntraMasthe 10",
    "familiaSlug": "intramasthe-10",
    "especie": "bovinos",
    "especies": [
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos"
    ],
    "categorias": [
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos"
    ],
    "segmentos": [
      "Bovinos de Leite"
    ],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Multiespécie (5 espécies)",
    "busca": "intramasthe 10 intramasthe 10 bovinos bubalinos caprinos equinos ovinos bovinos de leite"
  },
  {
    "id": "macru-h1000",
    "nome": "Macru H1000",
    "foto": "assets/images/produtos/Hagil_Bovinos_Bovinos 1ª Fase_Macru H1000.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Macru H1000.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Macru H1000-card.webp",
    "largura": 828,
    "altura": 1100,
    "cardLargura": 346,
    "cardAltura": 460,
    "largo": false,
    "familia": "Macru",
    "familiaSlug": "macru",
    "especie": "bovinos",
    "especies": [
      "aves",
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "peixes",
      "suinos"
    ],
    "categorias": [
      "aves",
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "peixes",
      "suinos"
    ],
    "segmentos": [
      "Aves de Corte",
      "Aves de Postura",
      "Bovinos 1ª Fase",
      "Bovinos de Corte",
      "Bovinos de Leite"
    ],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Multiespécie (8 espécies)",
    "busca": "macru h1000 macru aves bovinos bubalinos caprinos equinos ovinos peixes suinos aves de corte aves de postura bovinos 1ª fase bovinos de corte bovinos de leite"
  },
  {
    "id": "masthe-hmc1000",
    "nome": "Masthe HMC1000",
    "foto": "assets/images/produtos/Hagil_Bovinos_Bovinos de Corte_Masthe HMC1000.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos de Corte_Masthe HMC1000.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos de Corte_Masthe HMC1000-card.webp",
    "largura": 827,
    "altura": 1100,
    "cardLargura": 346,
    "cardAltura": 460,
    "largo": false,
    "familia": "Masthe",
    "familiaSlug": "masthe",
    "especie": "bovinos",
    "especies": [
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "suinos"
    ],
    "categorias": [
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "suinos"
    ],
    "segmentos": [
      "Bovinos de Corte",
      "Bovinos de Leite"
    ],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Multiespécie (6 espécies)",
    "busca": "masthe hmc1000 masthe bovinos bubalinos caprinos equinos ovinos suinos bovinos de corte bovinos de leite"
  },
  {
    "id": "muhlus",
    "nome": "Muhlus",
    "foto": "assets/images/produtos/Hagil_Pet_Muhlus.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Pet_Muhlus.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Pet_Muhlus-card.webp",
    "largura": 928,
    "altura": 1100,
    "cardLargura": 388,
    "cardAltura": 460,
    "largo": false,
    "familia": "Muhlus",
    "familiaSlug": "muhlus",
    "especie": "pet",
    "especies": [
      "pet"
    ],
    "categorias": [
      "pet"
    ],
    "segmentos": [],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Pet",
    "busca": "muhlus muhlus pet "
  },
  {
    "id": "maximo-baby-h1000",
    "nome": "Máximo Baby H1000",
    "foto": "assets/images/produtos/Hagil_Bovinos_Bovinos 1ª Fase_Máximo Baby H1000.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Máximo Baby H1000.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Máximo Baby H1000-card.webp",
    "largura": 845,
    "altura": 1100,
    "cardLargura": 353,
    "cardAltura": 460,
    "largo": false,
    "familia": "Máximo Baby",
    "familiaSlug": "maximo-baby",
    "especie": "bovinos",
    "especies": [
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "suinos"
    ],
    "categorias": [
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "suinos"
    ],
    "segmentos": [
      "Bovinos 1ª Fase"
    ],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Multiespécie (6 espécies)",
    "busca": "maximo baby h1000 maximo baby bovinos bubalinos caprinos equinos ovinos suinos bovinos 1ª fase"
  },
  {
    "id": "maximo-c-h1000",
    "nome": "Máximo C H1000",
    "foto": "assets/images/produtos/Hagil_Bovinos_Bovinos de Corte_Máximo C H1000.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos de Corte_Máximo C H1000.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos de Corte_Máximo C H1000-card.webp",
    "largura": 842,
    "altura": 1100,
    "cardLargura": 352,
    "cardAltura": 460,
    "largo": false,
    "familia": "Máximo C",
    "familiaSlug": "maximo-c",
    "especie": "bovinos",
    "especies": [
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "peixes"
    ],
    "categorias": [
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "peixes"
    ],
    "segmentos": [
      "Bovinos de Corte"
    ],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Multiespécie (6 espécies)",
    "busca": "maximo c h1000 maximo c bovinos bubalinos caprinos equinos ovinos peixes bovinos de corte"
  },
  {
    "id": "maximo-l-h1000",
    "nome": "Máximo L H1000",
    "foto": "assets/images/produtos/Hagil_Bovinos_Bovinos de Corte_Máximo L H1000.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos de Corte_Máximo L H1000.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos de Corte_Máximo L H1000-card.webp",
    "largura": 843,
    "altura": 1100,
    "cardLargura": 353,
    "cardAltura": 460,
    "largo": false,
    "familia": "Máximo L",
    "familiaSlug": "maximo-l",
    "especie": "bovinos",
    "especies": [
      "aves",
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "suinos"
    ],
    "categorias": [
      "aves",
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "suinos"
    ],
    "segmentos": [
      "Aves de Corte",
      "Aves de Postura",
      "Bovinos de Corte",
      "Bovinos de Leite"
    ],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Multiespécie (7 espécies)",
    "busca": "maximo l h1000 maximo l aves bovinos bubalinos caprinos equinos ovinos suinos aves de corte aves de postura bovinos de corte bovinos de leite"
  },
  {
    "id": "olhim",
    "nome": "Olhim",
    "foto": "assets/images/produtos/Hagil_Pet_Olhim.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Pet_Olhim.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Pet_Olhim-card.webp",
    "largura": 584,
    "altura": 1100,
    "cardLargura": 244,
    "cardAltura": 460,
    "largo": false,
    "familia": "Olhim",
    "familiaSlug": "olhim",
    "especie": "pet",
    "especies": [
      "pet"
    ],
    "categorias": [
      "pet"
    ],
    "segmentos": [],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Pet",
    "busca": "olhim olhim pet "
  },
  {
    "id": "pipih-pet",
    "nome": "Pipih pet",
    "foto": "assets/images/produtos/Hagil_Pet_Pipih pet.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Pet_Pipih pet.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Pet_Pipih pet-card.webp",
    "largura": 937,
    "altura": 1100,
    "cardLargura": 392,
    "cardAltura": 460,
    "largo": false,
    "familia": "Pipih",
    "familiaSlug": "pipih",
    "especie": "pet",
    "especies": [
      "pet"
    ],
    "categorias": [
      "pet"
    ],
    "segmentos": [],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Pet",
    "busca": "pipih pet pipih pet "
  },
  {
    "id": "qualis-h1000",
    "nome": "Qualis H1000",
    "foto": "assets/images/produtos/Hagil_Bovinos_Bovinos de Leite_Qualis H1000.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos de Leite_Qualis H1000.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos de Leite_Qualis H1000-card.webp",
    "largura": 855,
    "altura": 1100,
    "cardLargura": 358,
    "cardAltura": 460,
    "largo": false,
    "familia": "Qualis",
    "familiaSlug": "qualis",
    "especie": "bovinos",
    "especies": [
      "bovinos",
      "bubalinos"
    ],
    "categorias": [
      "bovinos",
      "bubalinos"
    ],
    "segmentos": [
      "Bovinos de Leite"
    ],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Bovinos, Bubalinos",
    "busca": "qualis h1000 qualis bovinos bubalinos bovinos de leite"
  },
  {
    "id": "reproducao-gold",
    "nome": "Reprodução Gold",
    "foto": "assets/images/produtos/Hagil_Bovinos_Bovinos de Corte_Reprodução Gold.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos de Corte_Reprodução Gold.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos de Corte_Reprodução Gold-card.webp",
    "largura": 844,
    "altura": 1100,
    "cardLargura": 353,
    "cardAltura": 460,
    "largo": false,
    "familia": "Reprodução Gold",
    "familiaSlug": "reproducao-gold",
    "especie": "bovinos",
    "especies": [
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "suinos"
    ],
    "categorias": [
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "suinos"
    ],
    "segmentos": [
      "Bovinos de Corte",
      "Bovinos de Leite"
    ],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Multiespécie (6 espécies)",
    "busca": "reproducao gold reproducao gold bovinos bubalinos caprinos equinos ovinos suinos bovinos de corte bovinos de leite"
  },
  {
    "id": "silencio",
    "nome": "Silencio",
    "foto": "assets/images/produtos/Hagil_Pet_Silencio.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Pet_Silencio.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Pet_Silencio-card.webp",
    "largura": 938,
    "altura": 1100,
    "cardLargura": 392,
    "cardAltura": 460,
    "largo": false,
    "familia": "Silencio",
    "familiaSlug": "silencio",
    "especie": "pet",
    "especies": [
      "pet"
    ],
    "categorias": [
      "pet"
    ],
    "segmentos": [],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Pet",
    "busca": "silencio silencio pet "
  },
  {
    "id": "verruther-hp1000",
    "nome": "Verruther HP1000",
    "foto": "assets/images/produtos/Hagil_Bovinos_Bovinos 1ª Fase_Verruther HP1000.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Verruther HP1000.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Bovinos_Bovinos 1ª Fase_Verruther HP1000-card.webp",
    "largura": 840,
    "altura": 1100,
    "cardLargura": 351,
    "cardAltura": 460,
    "largo": false,
    "familia": "Verruther",
    "familiaSlug": "verruther",
    "especie": "bovinos",
    "especies": [
      "aves",
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "peixes",
      "suinos"
    ],
    "categorias": [
      "aves",
      "bovinos",
      "bubalinos",
      "caprinos",
      "equinos",
      "ovinos",
      "peixes",
      "suinos"
    ],
    "segmentos": [
      "Aves de Corte",
      "Aves de Postura",
      "Bovinos 1ª Fase",
      "Bovinos de Corte",
      "Bovinos de Leite"
    ],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Multiespécie (8 espécies)",
    "busca": "verruther hp1000 verruther aves bovinos bubalinos caprinos equinos ovinos peixes suinos aves de corte aves de postura bovinos 1ª fase bovinos de corte bovinos de leite"
  },
  {
    "id": "virtus-hv1000",
    "nome": "Virtus HV1000",
    "foto": "assets/images/produtos/Hagil_Caprinos_Virtus HV1000.png",
    "imagem": "assets/images/produtos/otimizados/Hagil_Caprinos_Virtus HV1000.webp",
    "imagemCard": "assets/images/produtos/otimizados/Hagil_Caprinos_Virtus HV1000-card.webp",
    "largura": 837,
    "altura": 1100,
    "cardLargura": 350,
    "cardAltura": 460,
    "largo": false,
    "familia": "Virtus",
    "familiaSlug": "virtus",
    "especie": "caprinos",
    "especies": [
      "caprinos",
      "ovinos"
    ],
    "categorias": [
      "caprinos",
      "ovinos"
    ],
    "segmentos": [],
    "beneficio": "",
    "indicacoesTecnicas": "",
    "composicao": "",
    "modoUso": "",
    "registroMapa": "",
    "conteudoPendente": true,
    "categoriaRotulo": "Caprinos, Ovinos",
    "busca": "virtus hv1000 virtus caprinos ovinos "
  }
]
};
